import { DataGridColumn } from './types';

// Sample data interface
export interface SampleUser {
  id: string;
  name: string;
  email: string;
  age: number;
  department: string;
  salary: number;
  status: 'active' | 'inactive' | 'pending';
  joinDate: string;
  avatar: string;
  performance: number;
  location: string;
  manager: string;
}

// Sample data
export const sampleUsers: SampleUser[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    age: 28,
    department: 'Engineering',
    salary: 85000,
    status: 'active',
    joinDate: '2023-01-15',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50&h=50&fit=crop&crop=face',
    performance: 85,
    location: 'New York',
    manager: 'Sarah Wilson'
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    age: 32,
    department: 'Marketing',
    salary: 72000,
    status: 'active',
    joinDate: '2022-08-22',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b4e7bf8a?w=50&h=50&fit=crop&crop=face',
    performance: 92,
    location: 'San Francisco',
    manager: 'Mike Johnson'
  },
  {
    id: '3',
    name: 'Bob Wilson',
    email: 'bob.wilson@example.com',
    age: 45,
    department: 'Sales',
    salary: 95000,
    status: 'inactive',
    joinDate: '2021-03-10',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&h=50&fit=crop&crop=face',
    performance: 78,
    location: 'Chicago',
    manager: 'Lisa Davis'
  },
  {
    id: '4',
    name: 'Alice Brown',
    email: 'alice.brown@example.com',
    age: 29,
    department: 'Design',
    salary: 68000,
    status: 'pending',
    joinDate: '2023-06-01',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50&h=50&fit=crop&crop=face',
    performance: 88,
    location: 'Austin',
    manager: 'Tom Anderson'
  },
  {
    id: '5',
    name: 'Charlie Davis',
    email: 'charlie.davis@example.com',
    age: 35,
    department: 'Engineering',
    salary: 92000,
    status: 'active',
    joinDate: '2022-11-15',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&h=50&fit=crop&crop=face',
    performance: 94,
    location: 'Seattle',
    manager: 'Sarah Wilson'
  },
  {
    id: '6',
    name: 'Eva Green',
    email: 'eva.green@example.com',
    age: 27,
    department: 'HR',
    salary: 58000,
    status: 'active',
    joinDate: '2023-02-28',
    avatar: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=50&h=50&fit=crop&crop=face',
    performance: 76,
    location: 'Denver',
    manager: 'Rachel Green'
  },
  {
    id: '7',
    name: 'David Miller',
    email: 'david.miller@example.com',
    age: 41,
    department: 'Finance',
    salary: 78000,
    status: 'active',
    joinDate: '2021-07-12',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=50&h=50&fit=crop&crop=face',
    performance: 82,
    location: 'Boston',
    manager: 'Kevin Brown'
  },
  {
    id: '8',
    name: 'Grace Taylor',
    email: 'grace.taylor@example.com',
    age: 26,
    department: 'Marketing',
    salary: 65000,
    status: 'pending',
    joinDate: '2023-09-05',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=50&h=50&fit=crop&crop=face',
    performance: 89,
    location: 'Miami',
    manager: 'Mike Johnson'
  },
  {
    id: '9',
    name: 'Henry Wilson',
    email: 'henry.wilson@example.com',
    age: 38,
    department: 'Sales',
    salary: 87000,
    status: 'active',
    joinDate: '2022-04-18',
    avatar: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=50&h=50&fit=crop&crop=face',
    performance: 91,
    location: 'Phoenix',
    manager: 'Lisa Davis'
  },
  {
    id: '10',
    name: 'Ivy Chen',
    email: 'ivy.chen@example.com',
    age: 30,
    department: 'Engineering',
    salary: 89000,
    status: 'active',
    joinDate: '2022-12-03',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=50&h=50&fit=crop&crop=face',
    performance: 95,
    location: 'Portland',
    manager: 'Sarah Wilson'
  },
  {
    id: '11',
    name: 'John Doe',
    email: 'john.doe@example.com',
    age: 28,
    department: 'Engineering',
    salary: 85000,
    status: 'active',
    joinDate: '2023-01-15',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50&h=50&fit=crop&crop=face',
    performance: 85,
    location: 'New York',
    manager: 'Sarah Wilson'
  },
  {
    id: '12',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    age: 32,
    department: 'Marketing',
    salary: 72000,
    status: 'active',
    joinDate: '2022-08-22',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b4e7bf8a?w=50&h=50&fit=crop&crop=face',
    performance: 92,
    location: 'San Francisco',
    manager: 'Mike Johnson'
  },
  {
    id: '13',
    name: 'Bob Wilson',
    email: 'bob.wilson@example.com',
    age: 45,
    department: 'Sales',
    salary: 95000,
    status: 'inactive',
    joinDate: '2021-03-10',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&h=50&fit=crop&crop=face',
    performance: 78,
    location: 'Chicago',
    manager: 'Lisa Davis'
  },
  {
    id: '14',
    name: 'Alice Brown',
    email: 'alice.brown@example.com',
    age: 29,
    department: 'Design',
    salary: 68000,
    status: 'pending',
    joinDate: '2023-06-01',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50&h=50&fit=crop&crop=face',
    performance: 88,
    location: 'Austin',
    manager: 'Tom Anderson'
  },
  {
    id: '15',
    name: 'Charlie Davis',
    email: 'charlie.davis@example.com',
    age: 35,
    department: 'Engineering',
    salary: 92000,
    status: 'active',
    joinDate: '2022-11-15',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&h=50&fit=crop&crop=face',
    performance: 94,
    location: 'Seattle',
    manager: 'Sarah Wilson'
  },
  {
    id: '16',
    name: 'Eva Green',
    email: 'eva.green@example.com',
    age: 27,
    department: 'HR',
    salary: 58000,
    status: 'active',
    joinDate: '2023-02-28',
    avatar: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=50&h=50&fit=crop&crop=face',
    performance: 76,
    location: 'Denver',
    manager: 'Rachel Green'
  },
  {
    id: '17',
    name: 'David Miller',
    email: 'david.miller@example.com',
    age: 41,
    department: 'Finance',
    salary: 78000,
    status: 'active',
    joinDate: '2021-07-12',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=50&h=50&fit=crop&crop=face',
    performance: 82,
    location: 'Boston',
    manager: 'Kevin Brown'
  },
  {
    id: '18',
    name: 'Grace Taylor',
    email: 'grace.taylor@example.com',
    age: 26,
    department: 'Marketing',
    salary: 65000,
    status: 'pending',
    joinDate: '2023-09-05',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=50&h=50&fit=crop&crop=face',
    performance: 89,
    location: 'Miami',
    manager: 'Mike Johnson'
  },
  {
    id: '19',
    name: 'Henry Wilson',
    email: 'henry.wilson@example.com',
    age: 38,
    department: 'Sales',
    salary: 87000,
    status: 'active',
    joinDate: '2022-04-18',
    avatar: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=50&h=50&fit=crop&crop=face',
    performance: 91,
    location: 'Phoenix',
    manager: 'Lisa Davis'
  },
  {
    id: '20',
    name: 'Ivy Chen',
    email: 'ivy.chen@example.com',
    age: 30,
    department: 'Engineering',
    salary: 89000,
    status: 'active',
    joinDate: '2022-12-03',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=50&h=50&fit=crop&crop=face',
    performance: 95,
    location: 'Portland',
    manager: 'Sarah Wilson'
  },
];

// Column definitions with all features demonstrated
export const userColumns: DataGridColumn<SampleUser>[] = [
  {
    id: 'avatar',
    accessorKey: 'avatar',
    header: 'Avatar',
    type: 'image',
    editable: false,
    filterable: false,
    sortable: false,
    width: 80,
    pinnable: true,
  },
  {
    id: 'name',
    accessorKey: 'name',
    header: 'Full Name',
    type: 'text',
    editable: true,
    filterable: true,
    sortable: true,
    width: 200,
    pinnable: true,
  },
  {
    id: 'email',
    accessorKey: 'email',
    header: 'Email Address',
    type: 'text',
    editable: true,
    filterable: true,
    sortable: true,
    width: 250,
  },
  {
    id: 'age',
    accessorKey: 'age',
    header: 'Age',
    type: 'number',
    editable: true,
    filterable: true,
    sortable: true,
    width: 100,
  },
  {
    id: 'department',
    accessorKey: 'department',
    header: 'Department',
    type: 'select',
    editable: true,
    filterable: true,
    sortable: true,
    width: 150,
    options: [
      { label: 'Engineering', value: 'Engineering' },
      { label: 'Marketing', value: 'Marketing' },
      { label: 'Sales', value: 'Sales' },
      { label: 'Design', value: 'Design' },
      { label: 'HR', value: 'HR' },
      { label: 'Finance', value: 'Finance' },
    ],
  },
  {
    id: 'salary',
    accessorKey: 'salary',
    header: 'Salary',
    type: 'number',
    editable: true,
    filterable: true,
    sortable: true,
    width: 120,
  },
  {
    id: 'status',
    accessorKey: 'status',
    header: 'Status',
    type: 'badge',
    editable: true,
    filterable: true,
    sortable: true,
    width: 120,
    options: [
      { label: 'Active', value: 'active' },
      { label: 'Inactive', value: 'inactive' },
      { label: 'Pending', value: 'pending' },
    ],
  },
  {
    id: 'joinDate',
    accessorKey: 'joinDate',
    header: 'Join Date',
    type: 'date',
    editable: true,
    filterable: true,
    sortable: true,
    width: 130,
  },
  {
    id: 'performance',
    accessorKey: 'performance',
    header: 'Performance',
    type: 'chart',
    editable: true,
    filterable: true,
    sortable: true,
    width: 150,
  },
  {
    id: 'location',
    accessorKey: 'location',
    header: 'Location',
    type: 'text',
    editable: true,
    filterable: true,
    sortable: true,
    width: 120,
  },
  {
    id: 'manager',
    accessorKey: 'manager',
    header: 'Manager',
    type: 'text',
    editable: false,
    filterable: true,
    sortable: true,
    width: 150,
  },
];